const PostActionTypes = {
    UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
    FETCH_POST_LIST_START: 'FETCH_POST_LIST_START',
    FETCH_POST_LIST_SUCCESS: 'FETCH_POST_LIST_SUCCESS',
    FETCH_POST_LIST_FAILURE: 'FETCH_POST_LIST_FAILURE'
}

export default PostActionTypes;